# Tensors 

In [ ]:
import torch

## zeros()

In [ ]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [ ]:
w.size()

torch.Size([4, 3])

In [ ]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [ ]:
w = torch.randn(4,3)
w

tensor([[-2.3249, -0.8446,  0.5649],
        [ 0.2339, -0.1939, -2.1444],
        [-0.2087,  0.1349, -1.0265],
        [ 0.3023,  0.0678,  0.9715]])

In [ ]:
t = torch.randn_like(w)

In [ ]:
t

tensor([[-0.4981, -0.6681,  0.3445],
        [ 0.2837, -0.3213,  0.0912],
        [-1.1343,  1.4955,  0.2378],
        [-0.5464, -0.4939, -0.2708]])

## fill_()

In [ ]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [ ]:
w.view(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
t = w.view(12,1)

In [ ]:
t = w.view(6,-1)
t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

## numpy()

In [ ]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)