# Autograd with tensors

In [ ]:
import torch

In [ ]:
w = torch.randn(4,3,requires_grad = True)

In [ ]:
w

tensor([[ 0.3765, -0.3624,  0.4632],
        [-0.1694, -0.0039, -1.5887],
        [ 0.4395,  0.1981,  0.2774],
        [-1.4084, -0.1667, -0.1964]], requires_grad=True)

In [ ]:
w.requires_grad_(False)
w

tensor([[ 0.3765, -0.3624,  0.4632],
        [-0.1694, -0.0039, -1.5887],
        [ 0.4395,  0.1981,  0.2774],
        [-1.4084, -0.1667, -0.1964]])

In [ ]:
w.requires_grad_(True)

tensor([[ 0.3765, -0.3624,  0.4632],
        [-0.1694, -0.0039, -1.5887],
        [ 0.4395,  0.1981,  0.2774],
        [-1.4084, -0.1667, -0.1964]], requires_grad=True)

In [ ]:
y = torch.exp(w)
y

tensor([[1.4571, 0.6960, 1.5891],
        [0.8442, 0.9961, 0.2042],
        [1.5520, 1.2191, 1.3196],
        [0.2445, 0.8464, 0.8217]], grad_fn=<ExpBackward0>)

In [ ]:
y.grad_fn

In [ ]:
outp = y.mean()
outp

tensor(0.9825, grad_fn=<MeanBackward0>)

In [ ]:
print(w.grad)

None


In [ ]:
outp.backward()

In [ ]:
w.grad

tensor([[0.1214, 0.0580, 0.1324],
        [0.0703, 0.0830, 0.0170],
        [0.1293, 0.1016, 0.1100],
        [0.0204, 0.0705, 0.0685]])

In [ ]:
print(w.detach())

tensor([[ 0.3765, -0.3624,  0.4632],
        [-0.1694, -0.0039, -1.5887],
        [ 0.4395,  0.1981,  0.2774],
        [-1.4084, -0.1667, -0.1964]])


In [ ]:
print(outp.requires_grad)

with torch.no_grad():
    outp = (w+y).mean()

print(outp.requires_grad)

True
False
